version: '2'
services:
    demo-app:
        image: demo
        external_links:
            - demo-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/demo?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    demo-mysql:
        extends:
            file: mysql.yml
            service: demo-mysql
